# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 530)
        MainWindow.setMinimumSize(QtCore.QSize(480, 530))
        MainWindow.setMaximumSize(QtCore.QSize(480, 530))
        MainWindow.setWindowTitle("app-name app-ver")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/ui/images/ICU.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: 240, 240, 240;")
        MainWindow.setIconSize(QtCore.QSize(143, 383))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgBrkstr = QtWidgets.QFrame(self.centralwidget)
        self.imgBrkstr.setGeometry(QtCore.QRect(10, 20, 168, 450))
        self.imgBrkstr.setStyleSheet("background-image: url(:/src/ui/images/Image.png);")
        self.imgBrkstr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imgBrkstr.setObjectName("imgBrkstr")
        self.chkFullscreen = QtWidgets.QCheckBox(self.centralwidget)
        self.chkFullscreen.setGeometry(QtCore.QRect(350, 160, 81, 21))
        self.chkFullscreen.setToolTip("Play in Fullscreen Mode (<span style=\"font-weight:600;\">Note:</span> Windowed Mode overwrites other config options and may make LEGO Island unstable)")
        self.chkFullscreen.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkFullscreen.setText("Fullscreen")
        self.chkFullscreen.setCheckable(True)
        self.chkFullscreen.setObjectName("chkFullscreen")
        self.chkMusic = QtWidgets.QCheckBox(self.centralwidget)
        self.chkMusic.setGeometry(QtCore.QRect(350, 140, 61, 21))
        self.chkMusic.setToolTip("Toggle in-game music")
        self.chkMusic.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkMusic.setText("Music")
        self.chkMusic.setObjectName("chkMusic")
        self.chkJoystick = QtWidgets.QCheckBox(self.centralwidget)
        self.chkJoystick.setGeometry(QtCore.QRect(350, 180, 91, 21))
        self.chkJoystick.setToolTip("Play using a joystick or keyboard")
        self.chkJoystick.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkJoystick.setText("Use Joystick")
        self.chkJoystick.setObjectName("chkJoystick")
        self.chkSound = QtWidgets.QCheckBox(self.centralwidget)
        self.chkSound.setGeometry(QtCore.QRect(350, 220, 81, 21))
        self.chkSound.setToolTip("Toggle between 2D and 3D sound")
        self.chkSound.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkSound.setText("3D Sound")
        self.chkSound.setObjectName("chkSound")
        self.lbDisplay = QtWidgets.QLabel(self.centralwidget)
        self.lbDisplay.setGeometry(QtCore.QRect(260, 0, 141, 31))
        self.lbDisplay.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Display Settings</span></p></body></html>")
        self.lbDisplay.setObjectName("lbDisplay")
        self.line3 = QtWidgets.QFrame(self.centralwidget)
        self.line3.setGeometry(QtCore.QRect(212, 169, 90, 20))
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.line2 = QtWidgets.QFrame(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(365, 51, 101, 20))
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.line1 = QtWidgets.QFrame(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(200, 50, 101, 20))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.line4 = QtWidgets.QFrame(self.centralwidget)
        self.line4.setGeometry(QtCore.QRect(190, 250, 281, 20))
        self.line4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line4.setObjectName("line4")
        self.comboD3D = QtWidgets.QComboBox(self.centralwidget)
        self.comboD3D.setGeometry(QtCore.QRect(250, 320, 161, 22))
        self.comboD3D.setObjectName("comboD3D")
        self.comboD3D.addItem("")
        self.comboD3D.setItemText(0, "Ramp Emulation")
        self.comboD3D.addItem("")
        self.comboD3D.setItemText(1, "RGB Emulation")
        self.comboD3D.addItem("")
        self.comboD3D.setItemText(2, "Direct3D HAL")
        self.comboD3D.addItem("")
        self.comboD3D.setItemText(3, "MMX Emulation")
        self.lbAdvanced = QtWidgets.QLabel(self.centralwidget)
        self.lbAdvanced.setGeometry(QtCore.QRect(260, 260, 141, 31))
        self.lbAdvanced.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Advanced Settings</span></p></body></html>")
        self.lbAdvanced.setObjectName("lbAdvanced")
        self.lbDirect3D = QtWidgets.QLabel(self.centralwidget)
        self.lbDirect3D.setGeometry(QtCore.QRect(280, 300, 111, 17))
        self.lbDirect3D.setToolTip("Set the Direct3D device the game should use.<br>Ramp Emulation is highly recommended for maximum compatibility.")
        self.lbDirect3D.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.lbDirect3D.setText("<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Direct3D Devices</span></p></body></html>")
        self.lbDirect3D.setObjectName("lbDirect3D")
        self.chkDraw3D = QtWidgets.QCheckBox(self.centralwidget)
        self.chkDraw3D.setGeometry(QtCore.QRect(250, 350, 181, 21))
        self.chkDraw3D.setToolTip("TODO Correct me<br>Set 3D elements to run on the GPU rather than the CPU?")
        self.chkDraw3D.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkDraw3D.setText("Draw 3D to Video Memory")
        self.chkDraw3D.setObjectName("chkDraw3D")
        self.chkFlipSurface = QtWidgets.QCheckBox(self.centralwidget)
        self.chkFlipSurface.setGeometry(QtCore.QRect(250, 370, 181, 21))
        self.chkFlipSurface.setToolTip("TODO Write me")
        self.chkFlipSurface.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkFlipSurface.setText("Flip Video Memory Pages")
        self.chkFlipSurface.setObjectName("chkFlipSurface")
        self.chkCursor = QtWidgets.QCheckBox(self.centralwidget)
        self.chkCursor.setGeometry(QtCore.QRect(350, 200, 101, 21))
        self.chkCursor.setToolTip("Use in-game cursor")
        self.chkCursor.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkCursor.setText("Draw Cursor")
        self.chkCursor.setObjectName("chkCursor")
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(210, 480, 75, 23))
        self.btnReset.setText("Reset")
        self.btnReset.setObjectName("btnReset")
        self.leSaveDir = QtWidgets.QLineEdit(self.centralwidget)
        self.leSaveDir.setGeometry(QtCore.QRect(190, 440, 161, 21))
        self.leSaveDir.setToolTip("Current Save Game path")
        self.leSaveDir.setPlaceholderText("C:\\Program Files\\LEGO Island")
        self.leSaveDir.setObjectName("leSaveDir")
        self.lbSaveLoc = QtWidgets.QLabel(self.centralwidget)
        self.lbSaveLoc.setGeometry(QtCore.QRect(260, 400, 141, 31))
        self.lbSaveLoc.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Save Game Location</span></p></body></html>")
        self.lbSaveLoc.setObjectName("lbSaveLoc")
        self.line5 = QtWidgets.QFrame(self.centralwidget)
        self.line5.setGeometry(QtCore.QRect(190, 390, 281, 20))
        self.line5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line5.setObjectName("line5")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setEnabled(True)
        self.btnClose.setGeometry(QtCore.QRect(390, 480, 75, 23))
        self.btnClose.setText("Close")
        self.btnClose.setFlat(False)
        self.btnClose.setObjectName("btnClose")
        self.line6 = QtWidgets.QFrame(self.centralwidget)
        self.line6.setGeometry(QtCore.QRect(190, 460, 281, 20))
        self.line6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line6.setObjectName("line6")
        self.btnRedirect = QtWidgets.QPushButton(self.centralwidget)
        self.btnRedirect.setGeometry(QtCore.QRect(400, 440, 61, 23))
        self.btnRedirect.setToolTip("ReDirect current game saves to new location")
        self.btnRedirect.setText("ReDirect")
        self.btnRedirect.setObjectName("btnRedirect")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(198, 150, 121, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridColors = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridColors.setObjectName("gridColors")
        self.radioColor16b = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioColor16b.setToolTip("Select a color depth")
        self.radioColor16b.setText("High Color (16bit)")
        self.radioColor16b.setObjectName("radioColor16b")
        self.gridColors.addWidget(self.radioColor16b, 2, 0, 1, 1)
        self.radioColor256 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioColor256.setToolTip("Select a color depth")
        self.radioColor256.setText("256 Color")
        self.radioColor256.setObjectName("radioColor256")
        self.gridColors.addWidget(self.radioColor256, 1, 0, 1, 1)
        self.lbColorPal = QtWidgets.QLabel(self.layoutWidget)
        self.lbColorPal.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.lbColorPal.setText("<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Color Palette</span></p></body></html>")
        self.lbColorPal.setObjectName("lbColorPal")
        self.gridColors.addWidget(self.lbColorPal, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 30, 106, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridModelQual = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridModelQual.setObjectName("gridModelQual")
        self.lbModelQual = QtWidgets.QLabel(self.layoutWidget1)
        self.lbModelQual.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.lbModelQual.setText("<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Model Quality</span></p></body></html>")
        self.lbModelQual.setObjectName("lbModelQual")
        self.gridModelQual.addWidget(self.lbModelQual, 0, 0, 1, 1)
        self.radioModelFast = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioModelFast.setToolTip("3D Model Quality")
        self.radioModelFast.setText("Fast")
        self.radioModelFast.setObjectName("radioModelFast")
        self.gridModelQual.addWidget(self.radioModelFast, 2, 0, 1, 1)
        self.radioModelHigh = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioModelHigh.setToolTip("3D Model Quality")
        self.radioModelHigh.setText("High")
        self.radioModelHigh.setObjectName("radioModelHigh")
        self.gridModelQual.addWidget(self.radioModelHigh, 3, 0, 1, 1)
        self.radioModelLow = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioModelLow.setToolTip("3D Model Quality")
        self.radioModelLow.setText("Low")
        self.radioModelLow.setObjectName("radioModelLow")
        self.gridModelQual.addWidget(self.radioModelLow, 1, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(360, 30, 111, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridTexQual = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridTexQual.setObjectName("gridTexQual")
        self.radioTexFast = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioTexFast.setToolTip("Texture Quality")
        self.radioTexFast.setText("Fast")
        self.radioTexFast.setObjectName("radioTexFast")
        self.gridTexQual.addWidget(self.radioTexFast, 1, 0, 1, 1)
        self.radioTexHigh = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioTexHigh.setToolTip("Texture Quality")
        self.radioTexHigh.setText("High")
        self.radioTexHigh.setObjectName("radioTexHigh")
        self.gridTexQual.addWidget(self.radioTexHigh, 2, 0, 1, 1)
        self.lbTextureQual = QtWidgets.QLabel(self.layoutWidget2)
        self.lbTextureQual.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.lbTextureQual.setText("<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Texture Quality</span></p></body></html>")
        self.lbTextureQual.setObjectName("lbTextureQual")
        self.gridTexQual.addWidget(self.lbTextureQual, 0, 0, 1, 1)
        self.btnBrowse = QtWidgets.QToolButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(360, 440, 25, 19))
        self.btnBrowse.setToolTip("Browse")
        self.btnBrowse.setText("...")
        self.btnBrowse.setObjectName("btnBrowse")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(300, 480, 75, 23))
        self.btnApply.setText("Apply")
        self.btnApply.setObjectName("btnApply")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.imgBrkstr.raise_()
        self.layoutWidget.raise_()
        self.chkFullscreen.raise_()
        self.chkMusic.raise_()
        self.chkJoystick.raise_()
        self.chkSound.raise_()
        self.lbDisplay.raise_()
        self.line3.raise_()
        self.line2.raise_()
        self.line1.raise_()
        self.line4.raise_()
        self.comboD3D.raise_()
        self.lbAdvanced.raise_()
        self.lbDirect3D.raise_()
        self.chkDraw3D.raise_()
        self.chkFlipSurface.raise_()
        self.chkCursor.raise_()
        self.btnReset.raise_()
        self.leSaveDir.raise_()
        self.lbSaveLoc.raise_()
        self.line5.raise_()
        self.btnClose.raise_()
        self.line6.raise_()
        self.btnRedirect.raise_()
        self.btnBrowse.raise_()
        self.btnApply.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionQuit.setFont(font)
        self.actionQuit.setObjectName("actionQuit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setEnabled(True)
        self.actionAbout.setObjectName("actionAbout")
        self.actionApply = QtWidgets.QAction(MainWindow)
        self.actionApply.setObjectName("actionApply")
        self.menuFile.addAction(self.actionApply)
        self.menuFile.addAction(self.actionReset)
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioModelLow, self.radioModelFast)
        MainWindow.setTabOrder(self.radioModelFast, self.radioModelHigh)
        MainWindow.setTabOrder(self.radioModelHigh, self.radioTexFast)
        MainWindow.setTabOrder(self.radioTexFast, self.radioTexHigh)
        MainWindow.setTabOrder(self.radioTexHigh, self.radioColor256)
        MainWindow.setTabOrder(self.radioColor256, self.radioColor16b)
        MainWindow.setTabOrder(self.radioColor16b, self.chkMusic)
        MainWindow.setTabOrder(self.chkMusic, self.chkFullscreen)
        MainWindow.setTabOrder(self.chkFullscreen, self.chkJoystick)
        MainWindow.setTabOrder(self.chkJoystick, self.chkCursor)
        MainWindow.setTabOrder(self.chkCursor, self.chkSound)
        MainWindow.setTabOrder(self.chkSound, self.comboD3D)
        MainWindow.setTabOrder(self.comboD3D, self.chkDraw3D)
        MainWindow.setTabOrder(self.chkDraw3D, self.chkFlipSurface)
        MainWindow.setTabOrder(self.chkFlipSurface, self.leSaveDir)
        MainWindow.setTabOrder(self.leSaveDir, self.btnBrowse)
        MainWindow.setTabOrder(self.btnBrowse, self.btnRedirect)
        MainWindow.setTabOrder(self.btnRedirect, self.btnReset)
        MainWindow.setTabOrder(self.btnReset, self.btnApply)
        MainWindow.setTabOrder(self.btnApply, self.btnClose)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "&Reset"))
        self.actionReset.setToolTip(_translate("MainWindow", "Reset"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F12"))
        self.actionApply.setText(_translate("MainWindow", "&Apply"))

import graphics_rc
