# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 488)
        MainWindow.setMinimumSize(QtCore.QSize(472, 488))
        MainWindow.setMaximumSize(QtCore.QSize(472, 488))
        MainWindow.setWindowTitle("app-name app-ver")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/ui/images/ICU.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: 240, 240, 240;")
        MainWindow.setIconSize(QtCore.QSize(143, 383))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgBrkstr = QtWidgets.QFrame(self.centralwidget)
        self.imgBrkstr.setGeometry(QtCore.QRect(10, 10, 168, 450))
        self.imgBrkstr.setStyleSheet("background-image: url(:/src/ui/images/Image.png);")
        self.imgBrkstr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imgBrkstr.setObjectName("imgBrkstr")
        self.chkWindowed = QtWidgets.QCheckBox(self.centralwidget)
        self.chkWindowed.setGeometry(QtCore.QRect(340, 140, 81, 21))
        self.chkWindowed.setToolTip("Enable Windowed Mode (<span style=\" font-weight:600;\">Note:</span> Windowed Mode overwrites other config options and may make LEGO Island unstable.)")
        self.chkWindowed.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkWindowed.setText("Windowed")
        self.chkWindowed.setCheckable(True)
        self.chkWindowed.setObjectName("chkWindowed")
        self.chkMusic = QtWidgets.QCheckBox(self.centralwidget)
        self.chkMusic.setGeometry(QtCore.QRect(340, 100, 61, 21))
        self.chkMusic.setToolTip("Toggle in-game music")
        self.chkMusic.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkMusic.setText("Music")
        self.chkMusic.setObjectName("chkMusic")
        self.chkJoystick = QtWidgets.QCheckBox(self.centralwidget)
        self.chkJoystick.setGeometry(QtCore.QRect(340, 200, 91, 21))
        self.chkJoystick.setToolTip("Enable joystick support")
        self.chkJoystick.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkJoystick.setText("Use Joystick")
        self.chkJoystick.setObjectName("chkJoystick")
        self.chkSound = QtWidgets.QCheckBox(self.centralwidget)
        self.chkSound.setGeometry(QtCore.QRect(340, 120, 81, 21))
        self.chkSound.setToolTip("Toggle between 2D and 3D sound")
        self.chkSound.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkSound.setText("3D Sound")
        self.chkSound.setObjectName("chkSound")
        self.lbDisplay = QtWidgets.QLabel(self.centralwidget)
        self.lbDisplay.setGeometry(QtCore.QRect(250, 0, 141, 31))
        self.lbDisplay.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Display Settings</span></p></body></html>")
        self.lbDisplay.setObjectName("lbDisplay")
        self.line4 = QtWidgets.QFrame(self.centralwidget)
        self.line4.setGeometry(QtCore.QRect(190, 220, 281, 20))
        self.line4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line4.setObjectName("line4")
        self.comboD3D = QtWidgets.QComboBox(self.centralwidget)
        self.comboD3D.setGeometry(QtCore.QRect(250, 280, 161, 22))
        self.comboD3D.setObjectName("comboD3D")
        self.comboD3D.addItem("")
        self.comboD3D.setItemText(0, "Ramp Emulation")
        self.comboD3D.addItem("")
        self.comboD3D.setItemText(1, "RGB Emulation")
        self.comboD3D.addItem("")
        self.comboD3D.setItemText(2, "Direct3D HAL")
        self.comboD3D.addItem("")
        self.comboD3D.setItemText(3, "MMX Emulation")
        self.lbAdvanced = QtWidgets.QLabel(self.centralwidget)
        self.lbAdvanced.setGeometry(QtCore.QRect(260, 230, 141, 31))
        self.lbAdvanced.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Advanced Settings</span></p></body></html>")
        self.lbAdvanced.setObjectName("lbAdvanced")
        self.lbDirect3D = QtWidgets.QLabel(self.centralwidget)
        self.lbDirect3D.setGeometry(QtCore.QRect(280, 260, 111, 17))
        self.lbDirect3D.setToolTip("Set the Direct3D device the game should use.<br>Ramp Emulation is highly recommended for maximum compatibility.")
        self.lbDirect3D.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.lbDirect3D.setText("<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Direct3D Devices</span></p></body></html>")
        self.lbDirect3D.setObjectName("lbDirect3D")
        self.chkDraw3D = QtWidgets.QCheckBox(self.centralwidget)
        self.chkDraw3D.setGeometry(QtCore.QRect(250, 310, 181, 21))
        self.chkDraw3D.setToolTip("TODO Correct me<br>Set 3D elements to run on the GPU rather than the CPU?")
        self.chkDraw3D.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkDraw3D.setText("Draw 3D to Video Memory")
        self.chkDraw3D.setObjectName("chkDraw3D")
        self.chkFlipSurface = QtWidgets.QCheckBox(self.centralwidget)
        self.chkFlipSurface.setGeometry(QtCore.QRect(250, 330, 181, 21))
        self.chkFlipSurface.setToolTip("TODO Write me")
        self.chkFlipSurface.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkFlipSurface.setText("Flip Video Memory Pages")
        self.chkFlipSurface.setObjectName("chkFlipSurface")
        self.chkCursor = QtWidgets.QCheckBox(self.centralwidget)
        self.chkCursor.setGeometry(QtCore.QRect(340, 180, 101, 21))
        self.chkCursor.setToolTip("Use in-game mouse cursor")
        self.chkCursor.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkCursor.setText("Draw Cursor")
        self.chkCursor.setObjectName("chkCursor")
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(210, 430, 75, 23))
        self.btnReset.setText("Reset")
        self.btnReset.setObjectName("btnReset")
        self.leSaveDir = QtWidgets.QLineEdit(self.centralwidget)
        self.leSaveDir.setGeometry(QtCore.QRect(190, 390, 161, 21))
        self.leSaveDir.setToolTip("Current Save Game path")
        self.leSaveDir.setPlaceholderText("C:\\Program Files\\LEGO Island")
        self.leSaveDir.setObjectName("leSaveDir")
        self.lbSaveLoc = QtWidgets.QLabel(self.centralwidget)
        self.lbSaveLoc.setGeometry(QtCore.QRect(260, 360, 141, 31))
        self.lbSaveLoc.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Save Game Location</span></p></body></html>")
        self.lbSaveLoc.setObjectName("lbSaveLoc")
        self.line5 = QtWidgets.QFrame(self.centralwidget)
        self.line5.setGeometry(QtCore.QRect(190, 350, 281, 20))
        self.line5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line5.setObjectName("line5")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setEnabled(True)
        self.btnClose.setGeometry(QtCore.QRect(390, 430, 75, 23))
        self.btnClose.setText("Close")
        self.btnClose.setFlat(False)
        self.btnClose.setObjectName("btnClose")
        self.line6 = QtWidgets.QFrame(self.centralwidget)
        self.line6.setGeometry(QtCore.QRect(190, 410, 281, 20))
        self.line6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line6.setObjectName("line6")
        self.btnRedirect = QtWidgets.QPushButton(self.centralwidget)
        self.btnRedirect.setGeometry(QtCore.QRect(400, 390, 61, 23))
        self.btnRedirect.setToolTip("ReDirect current game saves to new location")
        self.btnRedirect.setText("ReDirect")
        self.btnRedirect.setObjectName("btnRedirect")
        self.btnBrowse = QtWidgets.QToolButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(360, 390, 25, 19))
        self.btnBrowse.setToolTip("Browse")
        self.btnBrowse.setText("...")
        self.btnBrowse.setObjectName("btnBrowse")
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        self.btnApply.setGeometry(QtCore.QRect(300, 430, 75, 23))
        self.btnApply.setText("Apply")
        self.btnApply.setObjectName("btnApply")
        self.chkWideAngle = QtWidgets.QCheckBox(self.centralwidget)
        self.chkWideAngle.setGeometry(QtCore.QRect(340, 160, 121, 21))
        self.chkWideAngle.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.chkWideAngle.setText("Wide Angle View")
        self.chkWideAngle.setObjectName("chkWideAngle")
        self.wdgtModelQual = QtWidgets.QWidget(self.centralwidget)
        self.wdgtModelQual.setGeometry(QtCore.QRect(200, 50, 71, 61))
        self.wdgtModelQual.setObjectName("wdgtModelQual")
        self.radioModelHigh = QtWidgets.QRadioButton(self.wdgtModelQual)
        self.radioModelHigh.setGeometry(QtCore.QRect(0, 40, 82, 17))
        self.radioModelHigh.setText("High")
        self.radioModelHigh.setObjectName("radioModelHigh")
        self.radioModelFast = QtWidgets.QRadioButton(self.wdgtModelQual)
        self.radioModelFast.setGeometry(QtCore.QRect(0, 20, 82, 17))
        self.radioModelFast.setText("Fast")
        self.radioModelFast.setObjectName("radioModelFast")
        self.radioModelLow = QtWidgets.QRadioButton(self.wdgtModelQual)
        self.radioModelLow.setGeometry(QtCore.QRect(0, 0, 82, 17))
        self.radioModelLow.setText("Low")
        self.radioModelLow.setObjectName("radioModelLow")
        self.radioModelHigh.raise_()
        self.radioModelFast.raise_()
        self.radioModelLow.raise_()
        self.wdgtTexQual = QtWidgets.QWidget(self.centralwidget)
        self.wdgtTexQual.setGeometry(QtCore.QRect(340, 50, 71, 41))
        self.wdgtTexQual.setObjectName("wdgtTexQual")
        self.radioTexHigh = QtWidgets.QRadioButton(self.wdgtTexQual)
        self.radioTexHigh.setGeometry(QtCore.QRect(0, 20, 82, 17))
        self.radioTexHigh.setText("High")
        self.radioTexHigh.setObjectName("radioTexHigh")
        self.radioTexFast = QtWidgets.QRadioButton(self.wdgtTexQual)
        self.radioTexFast.setGeometry(QtCore.QRect(0, 0, 82, 17))
        self.radioTexFast.setText("Fast")
        self.radioTexFast.setObjectName("radioTexFast")
        self.wdgtColorPal = QtWidgets.QWidget(self.centralwidget)
        self.wdgtColorPal.setGeometry(QtCore.QRect(200, 140, 120, 41))
        self.wdgtColorPal.setObjectName("wdgtColorPal")
        self.radioColor16b = QtWidgets.QRadioButton(self.wdgtColorPal)
        self.radioColor16b.setGeometry(QtCore.QRect(0, 20, 111, 17))
        self.radioColor16b.setText("High Color (16-bit)")
        self.radioColor16b.setObjectName("radioColor16b")
        self.radioColor256 = QtWidgets.QRadioButton(self.wdgtColorPal)
        self.radioColor256.setGeometry(QtCore.QRect(0, 0, 82, 17))
        self.radioColor256.setText("256 Color")
        self.radioColor256.setObjectName("radioColor256")
        self.lbModelQual = QtWidgets.QLabel(self.centralwidget)
        self.lbModelQual.setGeometry(QtCore.QRect(200, 30, 81, 21))
        self.lbModelQual.setText("<html><head/><body><p><span style=\" font-size:10pt;\">Model Quality</span></p></body></html>")
        self.lbModelQual.setObjectName("lbModelQual")
        self.lbTextQual = QtWidgets.QLabel(self.centralwidget)
        self.lbTextQual.setGeometry(QtCore.QRect(340, 30, 91, 21))
        self.lbTextQual.setText("<html><head/><body><p><span style=\" font-size:10pt;\">Texture Quality</span></p></body></html>")
        self.lbTextQual.setObjectName("lbTextQual")
        self.lbColorPal = QtWidgets.QLabel(self.centralwidget)
        self.lbColorPal.setGeometry(QtCore.QRect(200, 120, 81, 21))
        self.lbColorPal.setText("<html><head/><body><p><span style=\" font-size:10pt;\">Color Palette</span></p></body></html>")
        self.lbColorPal.setObjectName("lbColorPal")
        self.imgBrkstr.raise_()
        self.chkWindowed.raise_()
        self.chkMusic.raise_()
        self.chkJoystick.raise_()
        self.chkSound.raise_()
        self.lbDisplay.raise_()
        self.line4.raise_()
        self.comboD3D.raise_()
        self.lbAdvanced.raise_()
        self.lbDirect3D.raise_()
        self.chkDraw3D.raise_()
        self.chkFlipSurface.raise_()
        self.chkCursor.raise_()
        self.btnReset.raise_()
        self.leSaveDir.raise_()
        self.lbSaveLoc.raise_()
        self.line5.raise_()
        self.btnClose.raise_()
        self.line6.raise_()
        self.btnRedirect.raise_()
        self.btnBrowse.raise_()
        self.btnApply.raise_()
        self.lbModelQual.raise_()
        self.chkWideAngle.raise_()
        self.wdgtModelQual.raise_()
        self.wdgtTexQual.raise_()
        self.wdgtColorPal.raise_()
        self.lbModelQual.raise_()
        self.lbTextQual.raise_()
        self.radioModelFast.raise_()
        self.lbColorPal.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionQuit.setFont(font)
        self.actionQuit.setObjectName("actionQuit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setEnabled(True)
        self.actionAbout.setObjectName("actionAbout")
        self.actionApply = QtWidgets.QAction(MainWindow)
        self.actionApply.setObjectName("actionApply")
        self.menuFile.addAction(self.actionApply)
        self.menuFile.addAction(self.actionReset)
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.chkMusic, self.chkWindowed)
        MainWindow.setTabOrder(self.chkWindowed, self.chkJoystick)
        MainWindow.setTabOrder(self.chkJoystick, self.chkCursor)
        MainWindow.setTabOrder(self.chkCursor, self.chkSound)
        MainWindow.setTabOrder(self.chkSound, self.comboD3D)
        MainWindow.setTabOrder(self.comboD3D, self.chkDraw3D)
        MainWindow.setTabOrder(self.chkDraw3D, self.chkFlipSurface)
        MainWindow.setTabOrder(self.chkFlipSurface, self.leSaveDir)
        MainWindow.setTabOrder(self.leSaveDir, self.btnBrowse)
        MainWindow.setTabOrder(self.btnBrowse, self.btnRedirect)
        MainWindow.setTabOrder(self.btnRedirect, self.btnReset)
        MainWindow.setTabOrder(self.btnReset, self.btnApply)
        MainWindow.setTabOrder(self.btnApply, self.btnClose)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "&Reset"))
        self.actionReset.setToolTip(_translate("MainWindow", "Reset"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F12"))
        self.actionApply.setText(_translate("MainWindow", "&Apply"))

import graphics_rc
